### ISSUE TITLE
missing pokemon folder

### ISSUE THREAD

**Issue by hunch-13** [WatWowMap/MapJS#185]
without static/img/pokemon the site fails to load on a default install

**Comment by clburlison** [comment]
This is a discrepancy between the readme file and `config.example.json`. Adding more documentation for test setup, production setup including a sample nginx config, etc would help this along. Ideally I'd also love to have comments in the config file instead of the readme so it could be maintained in once place.

Just ransoms comments about the current state of documentation for the project for now.
